apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: naro-vorn9061-gitlab-next-ui-certificate
  namespace: naro-vorn9061-gitlab-next-ui
spec:
  secretName: naro-vorn9061-gitlab-next-ui-secret-tls
  commonName: naro-vorn9061-gitlab-next-ui.assessify.org
  dnsNames:
  - naro-vorn9061-gitlab-next-ui.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
